-- Chay file bo sung nay trong Supabase SQL Editor.
-- File nay co the chay lai nhieu lan, khong tao trung quyen/chuc nang.

create table if not exists public.system_connections (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  connection_type text not null,
  description text not null default '',
  config jsonb not null default '{}'::jsonb,
  is_active boolean not null default false,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

alter table public.system_connections enable row level security;

insert into public.features (code, name, parent_code, sort_order)
values
  ('admin.connections', 'Quản trị kết nối hệ thống', 'admin', 35),
  ('admin.connections.test', 'Kiểm tra kết nối hệ thống', 'admin.connections', 36)
on conflict (code) do update
set name = excluded.name,
    parent_code = excluded.parent_code,
    sort_order = excluded.sort_order;

insert into public.user_permissions (user_id, feature_code)
select u.id, f.code
from public.users u
cross join public.features f
where u.role = 'admin'
  and f.code in ('admin.connections', 'admin.connections.test')
on conflict do nothing;
