-- Chay file nay trong Supabase Dashboard > SQL Editor.
-- Luu y: ung dung hien tai tu quan ly dang nhap rieng, khong dung Supabase Auth.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  full_name text not null,
  employee_code text,
  email text,
  phone text,
  birth_date date,
  gender text,
  department text,
  job_title text,
  password_hash text not null,
  role text not null check (role in ('admin', 'viewer')),
  is_active boolean not null default true,
  must_change_password boolean not null default true,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create unique index if not exists users_username_lower_idx on public.users (lower(username));
create unique index if not exists users_employee_code_lower_idx on public.users (lower(employee_code)) where employee_code is not null;
create unique index if not exists users_email_lower_idx on public.users (lower(email)) where email is not null;

alter table public.users add column if not exists employee_code text;
alter table public.users add column if not exists email text;
alter table public.users add column if not exists phone text;
alter table public.users add column if not exists birth_date date;
alter table public.users add column if not exists gender text;
alter table public.users add column if not exists department text;
alter table public.users add column if not exists job_title text;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor text not null,
  action text not null,
  details text not null,
  created_at timestamptz not null
);

create table if not exists public.website_catalog (
  id bigint generated by default as identity primary key,
  name text not null unique,
  url text not null,
  requires_otp boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create unique index if not exists website_catalog_name_lower_idx on public.website_catalog (lower(name));

create table if not exists public.web_credentials (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  website_id bigint not null references public.website_catalog(id) on delete restrict,
  login_username text not null,
  encrypted_password text not null,
  notes text not null default '',
  created_at timestamptz not null,
  updated_at timestamptz not null,
  unique (user_id, website_id, login_username)
);

create index if not exists web_credentials_website_id_idx
on public.web_credentials (website_id);

create table if not exists public.features (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  parent_code text,
  sort_order integer not null default 0
);

create table if not exists public.user_permissions (
  user_id bigint not null references public.users(id) on delete cascade,
  feature_code text not null references public.features(code) on delete cascade,
  primary key (user_id, feature_code)
);

create index if not exists user_permissions_feature_code_idx
on public.user_permissions (feature_code);

create table if not exists public.system_roles (
  code text primary key,
  name text not null,
  description text not null default '',
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.system_connections (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  connection_type text not null,
  description text not null default '',
  config jsonb not null default '{}'::jsonb,
  is_active boolean not null default false,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.sql_reports (
  id bigint generated by default as identity primary key,
  ten_bao_cao text not null,
  ma_bao_cao text not null unique,
  cau_lenh_sql text not null,
  cac_tham_so jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists sql_reports_ma_bao_cao_lower_idx
on public.sql_reports (lower(ma_bao_cao));

create table if not exists public.onebss_reports (
  id bigint generated by default as identity primary key,
  ma_bao_cao text not null unique,
  ten_bao_cao text not null,
  danh_sach_bien jsonb not null default '[]'::jsonb,
  parameters jsonb not null default '{}'::jsonb,
  otp_service_code text not null default 'onebss',
  report_url text not null,
  storage_link text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.onebss_reports
add column if not exists parameters jsonb not null default '{}'::jsonb;

alter table public.onebss_reports
add column if not exists otp_service_code text not null default 'onebss';

create unique index if not exists onebss_reports_ma_bao_cao_lower_idx
on public.onebss_reports (lower(ma_bao_cao));

create table if not exists public.report_links (
  id bigint generated by default as identity primary key,
  ma_bao_cao text not null unique,
  ten_bao_cao text not null,
  link text not null,
  link_type text not null default 'other',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists report_links_ten_bao_cao_lower_idx
on public.report_links (lower(ten_bao_cao));

create unique index if not exists report_links_link_lower_idx
on public.report_links (lower(link));

create table if not exists public.onebss_report_runs (
  run_id text primary key,
  ma_bao_cao text not null,
  ten_bao_cao text not null default '',
  status text not null,
  message text not null default '',
  file_name text not null default '',
  file_path text not null default '',
  storage_link text not null default '',
  storage_status text not null default '',
  parameters jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms integer not null default 0,
  created_by text not null default '',
  worker_id text not null default '',
  worker_session_id text not null default '',
  otp_request_id text not null default '',
  claimed_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.onebss_report_runs
add column if not exists worker_id text not null default '';
alter table public.onebss_report_runs
add column if not exists worker_session_id text not null default '';
alter table public.onebss_report_runs
add column if not exists otp_request_id text not null default '';
alter table public.onebss_report_runs
add column if not exists claimed_at timestamptz;
alter table public.onebss_report_runs
add column if not exists updated_at timestamptz not null default now();

create index if not exists onebss_report_runs_report_idx
on public.onebss_report_runs (ma_bao_cao, started_at desc);

create table if not exists public.dashboard_layouts (
  page_id text primary key,
  page_name text not null,
  layout_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dashboard_chart_cache (
  chart_key text primary key,
  page_id text not null,
  tab_id text not null,
  widget_key text not null,
  report_id bigint,
  sql_code text not null,
  report_code text,
  report_name text,
  widget_title text,
  widget_type text,
  filters jsonb not null default '{}'::jsonb,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'success' check (status in ('success', 'error', 'refreshing')),
  error_message text,
  duration_ms integer,
  row_count integer not null default 0,
  refreshed_at timestamptz not null default now(),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists dashboard_chart_cache_report_id_idx
on public.dashboard_chart_cache (report_id);

create index if not exists dashboard_chart_cache_sql_code_idx
on public.dashboard_chart_cache (sql_code);

create index if not exists dashboard_chart_cache_expires_at_idx
on public.dashboard_chart_cache (expires_at);

insert into public.dashboard_layouts (page_id, page_name, layout_json, created_at, updated_at)
values (
  'DASHBOARD_KINH_DOANH',
  'Dashboard Kinh doanh',
  '{
    "page_id": "DASHBOARD_KINH_DOANH",
    "tabs": [
      {
        "tab_id": "tab_doanh_thu",
        "tab_name": "Doanh Thu Lõi",
        "order": 1,
        "grid_layout": [
          {
            "row_id": 1,
            "layout_type": "2_columns",
            "widgets": [
              {"position": 1, "type": "bar_chart", "title": "Di động", "sql_code": "BC_DI_DONG"},
              {"position": 2, "type": "pie_chart", "title": "Băng rộng", "sql_code": "BC_BANG_RONG"}
            ]
          }
        ]
      },
      {
        "tab_id": "tab_san_luong",
        "tab_name": "Sản lượng",
        "order": 2,
        "grid_layout": [
          {
            "row_id": 1,
            "layout_type": "4_columns",
            "widgets": [
              {"position": 1, "type": "metric", "title": "Fiber", "sql_code": "DASHBOARD_FIBER_VNPT"},
              {"position": 2, "type": "metric", "title": "MyTV", "sql_code": "BC_MYTV"},
              {"position": 3, "type": "metric", "title": "Mesh", "sql_code": "BC_MESH"},
              {"position": 4, "type": "metric", "title": "CAM", "sql_code": "BC_CAM"}
            ]
          }
        ]
      }
    ]
  }'::jsonb,
  now(),
  now()
)
on conflict (page_id) do nothing;

create table if not exists public.data_regions (
  code text primary key,
  name text not null,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.user_data_permissions (
  user_id bigint not null references public.users(id) on delete cascade,
  region_code text not null references public.data_regions(code) on delete cascade,
  primary key (user_id, region_code)
);

create index if not exists user_data_permissions_region_code_idx
on public.user_data_permissions (region_code);

create table if not exists public.work_tasks (
  task_id text primary key,
  ten_cong_viec text not null,
  schedule_type text not null default 'Daily',
  run_time text not null default '07:00',
  weekday text not null default '',
  once_date date,
  group_name text not null default '',
  is_done boolean not null default false,
  is_active boolean not null default true,
  last_notified_date date,
  last_notified_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.zalo_auto_messages (
  schedule_id text primary key,
  name text not null,
  page_url text not null default '/',
  page_label text not null default '',
  schedule_type text not null default 'Daily',
  time_slots jsonb not null default '[]'::jsonb,
  run_time text not null default '07:00',
  weekday text not null default '',
  month_day integer not null default 1,
  target_type text not null default 'group',
  chat_id text not null default '',
  chat_name text not null default '',
  caption text not null default '',
  photo_url text not null default '',
  is_active boolean not null default true,
  last_run_key text not null default '',
  last_sent_key text not null default '',
  last_sent_at timestamptz,
  last_error text not null default '',
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.zalo_message_captures (
  capture_id text primary key,
  schedule_id text not null references public.zalo_auto_messages(schedule_id) on delete cascade,
  mime_type text not null default 'image/png',
  image_base64 text not null,
  public_token text not null unique,
  page_url text not null default '',
  created_by text not null default '',
  created_at timestamptz not null
);

create index if not exists zalo_message_captures_schedule_idx
on public.zalo_message_captures (schedule_id, created_at desc);

create table if not exists public.data_mining_schedules (
  schedule_id text primary key,
  name text not null,
  report_url text not null,
  schedule_type text not null default 'Daily',
  run_time text not null default '07:00',
  weekday text not null default '',
  month_day integer not null default 1,
  storage_link text not null default '',
  file_name_template text not null default '',
  parameters jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  last_run_key text not null default '',
  last_success_key text not null default '',
  last_run_at timestamptz,
  last_success_at timestamptz,
  last_status text not null default '',
  last_error text not null default '',
  last_file_name text not null default '',
  last_file_path text not null default '',
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.data_mining_runs (
  run_id text primary key,
  schedule_id text not null references public.data_mining_schedules(schedule_id) on delete cascade,
  status text not null default 'running',
  message text not null default '',
  file_name text not null default '',
  file_path text not null default '',
  storage_link text not null default '',
  storage_status text not null default '',
  parameters jsonb not null default '{}'::jsonb,
  started_at timestamptz not null,
  finished_at timestamptz,
  duration_ms integer not null default 0,
  created_by text not null default ''
);

create index if not exists data_mining_runs_schedule_idx
on public.data_mining_runs (schedule_id, started_at desc);

create table if not exists public.login_attempts (
  username text primary key,
  fail_count integer not null default 0,
  last_ip text not null default '',
  last_failed_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.user_login_sessions (
  session_id text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  username text not null default '',
  ip_address text not null default '',
  user_agent text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null,
  last_seen_at timestamptz not null,
  revoked_at timestamptz,
  revoked_reason text not null default ''
);

create index if not exists user_login_sessions_active_idx
on public.user_login_sessions (user_id, is_active, created_at desc);

create table if not exists public.billing_plans (
  code text primary key,
  name text not null,
  paid_months integer not null,
  bonus_months integer not null default 0,
  price_vnd bigint not null default 0,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

insert into public.billing_plans (code, name, paid_months, bonus_months, price_vnd, is_active, sort_order, created_at, updated_at)
values
  ('monthly', '1 thang', 1, 0, 99000, true, 10, now(), now()),
  ('quarterly', '3 thang', 3, 0, 279000, true, 20, now(), now()),
  ('six_months', '6 thang tang 1', 6, 1, 539000, true, 30, now(), now()),
  ('yearly', '12 thang tang 2', 12, 2, 999000, true, 40, now(), now())
on conflict (code) do nothing;

create table if not exists public.user_billing (
  user_id bigint primary key references public.users(id) on delete cascade,
  billing_enabled boolean not null default false,
  plan_code text not null default 'monthly' references public.billing_plans(code),
  started_at timestamptz,
  expires_at timestamptz,
  status text not null default 'disabled',
  last_invoice_id text not null default '',
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create index if not exists user_billing_status_idx
on public.user_billing (billing_enabled, status, expires_at);

create table if not exists public.billing_invoices (
  invoice_id text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  plan_code text not null references public.billing_plans(code),
  amount_vnd bigint not null default 0,
  status text not null default 'pending',
  payment_code text not null unique,
  qr_payload text not null default '',
  created_at timestamptz not null,
  due_at timestamptz not null,
  paid_at timestamptz,
  updated_at timestamptz not null
);

create index if not exists billing_invoices_user_idx
on public.billing_invoices (user_id, created_at desc);

create table if not exists public.billing_payments (
  payment_id text primary key,
  invoice_id text not null references public.billing_invoices(invoice_id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  provider text not null default 'demo_vietqr',
  transaction_ref text not null default '',
  amount_vnd bigint not null default 0,
  raw_payload_json jsonb not null default '{}'::jsonb,
  paid_at timestamptz not null,
  created_at timestamptz not null
);

create index if not exists billing_payments_invoice_idx
on public.billing_payments (invoice_id);


-- Service/secret key cua backend se lam viec duoi quyen cao.
-- Neu bat RLS, nen tao policy rieng. Trong giai do noi bo, REST service key co the bypass RLS.
alter table public.users enable row level security;
alter table public.audit_logs enable row level security;
alter table public.website_catalog enable row level security;
alter table public.web_credentials enable row level security;
alter table public.features enable row level security;
alter table public.user_permissions enable row level security;
alter table public.system_roles enable row level security;
alter table public.system_connections enable row level security;
alter table public.data_regions enable row level security;
alter table public.user_data_permissions enable row level security;
alter table public.work_tasks enable row level security;
alter table public.zalo_auto_messages enable row level security;
alter table public.zalo_message_captures enable row level security;
alter table public.data_mining_schedules enable row level security;
alter table public.data_mining_runs enable row level security;
alter table public.login_attempts enable row level security;
alter table public.user_login_sessions enable row level security;
alter table public.sql_reports enable row level security;
alter table public.onebss_reports enable row level security;
alter table public.report_links enable row level security;
alter table public.onebss_report_runs enable row level security;
alter table public.dashboard_layouts enable row level security;
alter table public.dashboard_chart_cache enable row level security;
alter table public.billing_plans enable row level security;
alter table public.user_billing enable row level security;
alter table public.billing_invoices enable row level security;
alter table public.billing_payments enable row level security;

grant select, insert, update, delete on public.work_tasks to anon, authenticated, service_role;
grant select, insert, update, delete on public.zalo_auto_messages to service_role;
grant select, insert, update, delete on public.zalo_message_captures to service_role;
grant select, insert, update, delete on public.data_mining_schedules to service_role;
grant select, insert, update, delete on public.data_mining_runs to service_role;
grant select, insert, update, delete on public.login_attempts to anon, authenticated, service_role;
grant select, insert, update, delete on public.user_login_sessions to service_role;
grant select, insert, update, delete on public.sql_reports to anon, authenticated, service_role;
grant usage, select on sequence public.sql_reports_id_seq to anon, authenticated, service_role;
grant select, insert, update, delete on public.onebss_reports to anon, authenticated, service_role;
grant usage, select on sequence public.onebss_reports_id_seq to anon, authenticated, service_role;
grant select, insert, update, delete on public.report_links to service_role;
grant usage, select on sequence public.report_links_id_seq to service_role;
grant select, insert, update, delete on public.onebss_report_runs to anon, authenticated, service_role;
grant select, insert, update, delete on public.dashboard_layouts to service_role;
grant select, insert, update, delete on public.dashboard_chart_cache to service_role;
grant select on public.dashboard_chart_cache to anon, authenticated;
grant select, insert, update, delete on public.billing_plans to service_role;
grant select, insert, update, delete on public.user_billing to service_role;
grant select, insert, update, delete on public.billing_invoices to service_role;
grant select, insert, update, delete on public.billing_payments to service_role;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'zalo_auto_messages'
      and policyname = 'backend service can manage zalo auto messages'
  ) then
    create policy "backend service can manage zalo auto messages"
    on public.zalo_auto_messages
    for all
    to service_role
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'zalo_message_captures'
      and policyname = 'backend service can manage zalo message captures'
  ) then
    create policy "backend service can manage zalo message captures"
    on public.zalo_message_captures
    for all
    to service_role
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dashboard_chart_cache'
      and policyname = 'backend service can manage dashboard chart cache'
  ) then
    create policy "backend service can manage dashboard chart cache"
    on public.dashboard_chart_cache
    for all
    to service_role
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'data_mining_schedules'
      and policyname = 'backend service can manage data mining schedules'
  ) then
    create policy "backend service can manage data mining schedules"
    on public.data_mining_schedules
    for all
    to service_role
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'data_mining_runs'
      and policyname = 'backend service can manage data mining runs'
  ) then
    create policy "backend service can manage data mining runs"
    on public.data_mining_runs
    for all
    to service_role
    using (true)
      with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'onebss_reports'
      and policyname = 'backend service can manage onebss reports'
  ) then
    create policy "backend service can manage onebss reports"
    on public.onebss_reports
    for all
    to service_role
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'report_links'
      and policyname = 'backend service can manage report links'
  ) then
    create policy "backend service can manage report links"
    on public.report_links
    for all
    to service_role
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'onebss_report_runs'
      and policyname = 'backend service can manage onebss report runs'
  ) then
    create policy "backend service can manage onebss report runs"
    on public.onebss_report_runs
    for all
    to service_role
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dashboard_chart_cache'
      and policyname = 'anon can read dashboard chart cache'
  ) then
    create policy "anon can read dashboard chart cache"
    on public.dashboard_chart_cache
    for select
    to anon
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'dashboard_chart_cache'
      and policyname = 'authenticated can read dashboard chart cache'
  ) then
    create policy "authenticated can read dashboard chart cache"
    on public.dashboard_chart_cache
    for select
    to authenticated
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'user_login_sessions'
      and policyname = 'backend service can manage user login sessions'
  ) then
    create policy "backend service can manage user login sessions"
    on public.user_login_sessions
    for all
    to service_role
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'billing_plans'
      and policyname = 'backend service can manage billing plans'
  ) then
    create policy "backend service can manage billing plans"
    on public.billing_plans
    for all
    to service_role
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'user_billing'
      and policyname = 'backend service can manage user billing'
  ) then
    create policy "backend service can manage user billing"
    on public.user_billing
    for all
    to service_role
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'billing_invoices'
      and policyname = 'backend service can manage billing invoices'
  ) then
    create policy "backend service can manage billing invoices"
    on public.billing_invoices
    for all
    to service_role
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'billing_payments'
      and policyname = 'backend service can manage billing payments'
  ) then
    create policy "backend service can manage billing payments"
    on public.billing_payments
    for all
    to service_role
    using (true)
    with check (true);
  end if;
end $$;
