-- Run in Supabase Dashboard > SQL Editor.
-- Internal email IMAP sync storage for OTP discovery.

insert into public.features (code, name, parent_code, sort_order)
values
  ('internalemail', 'Mail nội bộ', 'quantriweb', 29),
  ('internal_email.view', 'Xem Mail nội bộ', 'internalemail', 281),
  ('internal_email.manage', 'Quản trị Mail nội bộ', 'internalemail', 282)
on conflict (code) do update
set name = excluded.name,
    parent_code = excluded.parent_code,
    sort_order = excluded.sort_order;

insert into public.user_permissions (user_id, feature_code)
select u.id, f.code
from public.users u
join public.features f on f.code in (
  'internalemail',
  'internal_email.view',
  'internal_email.manage'
)
where u.role = 'admin'
on conflict do nothing;

create table if not exists public.internal_email_messages (
  id bigint generated by default as identity primary key,
  account_key text not null default 'internal_email',
  mailbox text not null default 'INBOX',
  uid text not null,
  message_id text not null default '',
  sender text not null default '',
  sender_email text not null default '',
  subject text not null default '',
  body_masked text not null default '',
  received_at timestamptz not null,
  synced_at timestamptz not null default now(),
  is_otp_candidate boolean not null default false,
  otp_code_masked text not null default '',
  otp_service_code text not null default '',
  otp_request_id text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (account_key, mailbox, uid)
);

create index if not exists internal_email_messages_received_idx
on public.internal_email_messages (received_at desc, id desc);

create index if not exists internal_email_messages_otp_idx
on public.internal_email_messages (is_otp_candidate, received_at desc);

alter table public.internal_email_messages enable row level security;

revoke all on table public.internal_email_messages from anon, authenticated;
grant select, insert, update, delete on table public.internal_email_messages to service_role;
grant usage, select on sequence public.internal_email_messages_id_seq to service_role;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'internal_email_messages'
      and policyname = 'backend service can manage internal email messages'
  ) then
    create policy "backend service can manage internal email messages"
    on public.internal_email_messages
    for all
    to service_role
    using (true)
    with check (true);
  end if;
end $$;
