-- Mobile Gateway 1.3 incremental migration.
-- Safe operations only: add columns, create tables/indexes, grants, and seed rows.

alter table public.mobile_pairing_codes
  add column if not exists policy_payload jsonb not null default '{}'::jsonb;

alter table public.mobile_device_policies
  add column if not exists camera_enabled boolean not null default false;

alter table public.mobile_device_policies
  alter column minimum_app_version set default '1.3.0';

create table if not exists public.mobile_media (
  id bigint generated by default as identity primary key,
  device_id text not null,
  command_id text not null default '',
  media_type text not null,
  file_name text not null default '',
  mime_type text not null default '',
  size_bytes bigint not null default 0,
  captured_at timestamptz,
  uploaded_at timestamptz,
  drive_file_id text not null default '',
  drive_url text not null default '',
  status text not null default 'pending',
  error_message text not null default '',
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.otp_filter_configurations (
  id bigint generated by default as identity primary key,
  filter_id text not null unique,
  rule_name text not null,
  service_code text not null default 'onebss',
  sender_pattern text not null default '',
  sender_match_type text not null default 'contains',
  otp_length integer not null default 6,
  start_prefix text not null default '',
  validity_seconds integer not null default 60,
  enabled boolean not null default true,
  device_id text not null default '',
  sim_slot integer,
  priority integer not null default 100,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.otp_latest_values (
  id bigint generated by default as identity primary key,
  filter_id text not null default '',
  service_code text not null default '',
  rule_name text not null default '',
  sender text not null default '',
  code_masked text not null default '',
  received_at timestamptz not null,
  expires_at timestamptz not null,
  status text not null default 'valid',
  source_type text not null default '',
  source_id text not null default '',
  otp_request_id text not null default '',
  used_at timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create index if not exists mobile_media_device_idx on public.mobile_media (device_id, uploaded_at desc);
create index if not exists otp_filters_service_idx on public.otp_filter_configurations (service_code, enabled, priority);
create index if not exists otp_latest_values_filter_idx on public.otp_latest_values (filter_id, received_at desc);

insert into public.features (code, name, parent_code, sort_order)
values
  ('mobile_gateway.media.view', 'Xem media Mobile', 'mobilegateway', 304),
  ('mobile_gateway.media.manage', 'Quan tri media Mobile', 'mobilegateway', 305)
on conflict (code) do update
set name = excluded.name,
    parent_code = excluded.parent_code,
    sort_order = excluded.sort_order;

insert into public.user_permissions (user_id, feature_code)
select u.id, f.code
from public.users u
join public.features f on f.code in (
  'mobile_gateway.media.view',
  'mobile_gateway.media.manage'
)
where u.role = 'admin'
on conflict do nothing;

insert into public.otp_filter_configurations
(filter_id, rule_name, service_code, sender_pattern, sender_match_type, otp_length,
 start_prefix, validity_seconds, enabled, priority, created_at, updated_at)
values
('onebss', 'OneBSS mac dinh', 'onebss', 'VNPT', 'contains', 6,
 '', 60, true, 10, now(), now())
on conflict (filter_id) do update
set rule_name = excluded.rule_name,
    service_code = excluded.service_code,
    sender_pattern = excluded.sender_pattern,
    sender_match_type = excluded.sender_match_type,
    otp_length = excluded.otp_length,
    start_prefix = excluded.start_prefix,
    validity_seconds = excluded.validity_seconds,
    enabled = excluded.enabled,
    priority = excluded.priority,
    updated_at = now();

alter table public.mobile_media enable row level security;
alter table public.otp_filter_configurations enable row level security;
alter table public.otp_latest_values enable row level security;

revoke all on table public.mobile_media from anon, authenticated;
revoke all on table public.otp_filter_configurations from anon, authenticated;
revoke all on table public.otp_latest_values from anon, authenticated;

grant select, insert, update, delete on table public.mobile_media to service_role;
grant select, insert, update, delete on table public.otp_filter_configurations to service_role;
grant select, insert, update, delete on table public.otp_latest_values to service_role;
grant usage, select on all sequences in schema public to service_role;
