-- Run in Supabase Dashboard > SQL Editor.
-- Mobile Gateway / OTP schema. This migration only creates new tables, indexes, grants, and seed rows.

create table if not exists public.mobile_devices (
  id bigint generated by default as identity primary key,
  device_id text not null unique,
  name text not null default '',
  platform text not null default 'android',
  manufacturer text not null default '',
  model text not null default '',
  android_version text not null default '',
  app_version text not null default '',
  encrypted_device_secret text not null,
  is_active boolean not null default true,
  paired_at timestamptz,
  last_seen_at timestamptz,
  last_ip text not null default '',
  revoked_at timestamptz,
  created_by text not null default '',
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.mobile_pairing_codes (
  id bigint generated by default as identity primary key,
  code_hash text not null unique,
  created_by text not null default '',
  created_at timestamptz not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  used_by_device_id text,
  status text not null default 'active'
);

create table if not exists public.mobile_device_nonces (
  device_id text not null,
  nonce text not null,
  created_at timestamptz not null,
  expires_at timestamptz not null,
  primary key (device_id, nonce)
);

create table if not exists public.mobile_device_policies (
  device_id text primary key,
  sms_enabled boolean not null default true,
  notifications_enabled boolean not null default false,
  clipboard_enabled boolean not null default false,
  diagnostics_enabled boolean not null default true,
  notification_allowlist jsonb not null default '[]'::jsonb,
  heartbeat_interval_minutes integer not null default 15,
  sync_interval_minutes integer not null default 15,
  batch_size integer not null default 50,
  local_retention_days integer not null default 14,
  minimum_app_version text not null default '1.1.0',
  force_update boolean not null default false,
  updated_by text not null default '',
  updated_at timestamptz not null
);

create table if not exists public.mobile_device_heartbeats (
  id bigint generated by default as identity primary key,
  device_id text not null,
  app_version text not null default '',
  android_version text not null default '',
  manufacturer text not null default '',
  model text not null default '',
  battery_percent integer,
  charging boolean not null default false,
  network_type text not null default '',
  pending_sms integer not null default 0,
  pending_notifications integer not null default 0,
  sms_permission boolean not null default false,
  notification_access boolean not null default false,
  battery_optimization_ignored boolean not null default false,
  last_sms_received_at timestamptz,
  created_at timestamptz not null
);

create table if not exists public.mobile_sms_messages (
  id bigint generated by default as identity primary key,
  device_id text not null,
  external_id text not null,
  sender text not null,
  normalized_sender text not null,
  body_encrypted text not null,
  body_masked text not null default '',
  received_at timestamptz not null,
  subscription_id text not null default '',
  sim_slot integer,
  synced_at timestamptz not null,
  is_otp_candidate boolean not null default false,
  used_for_otp boolean not null default false,
  otp_request_id text,
  created_at timestamptz not null,
  unique (device_id, external_id)
);

create table if not exists public.mobile_notifications (
  id bigint generated by default as identity primary key,
  device_id text not null,
  external_id text not null,
  package_name text not null,
  app_name text not null default '',
  title text not null default '',
  text_encrypted text not null default '',
  text_masked text not null default '',
  posted_at timestamptz not null,
  used_for_otp boolean not null default false,
  otp_request_id text,
  created_at timestamptz not null,
  unique (device_id, external_id)
);

create table if not exists public.mobile_commands (
  command_id text primary key,
  device_id text not null,
  command_type text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  created_by text not null default '',
  created_at timestamptz not null,
  expires_at timestamptz not null,
  delivered_at timestamptz,
  acknowledged_at timestamptz,
  completed_at timestamptz,
  sanitized_error text not null default ''
);

create table if not exists public.mobile_command_logs (
  id bigint generated by default as identity primary key,
  command_id text not null,
  device_id text not null,
  status text not null,
  payload jsonb not null default '{}'::jsonb,
  sanitized_error text not null default '',
  created_at timestamptz not null
);

create table if not exists public.mobile_diagnostics (
  id bigint generated by default as identity primary key,
  device_id text not null,
  app_version text not null default '',
  android_version text not null default '',
  manufacturer text not null default '',
  model text not null default '',
  payload jsonb not null default '{}'::jsonb,
  sanitized_error text not null default '',
  created_at timestamptz not null
);

create table if not exists public.otp_configurations (
  id bigint generated by default as identity primary key,
  service_code text not null unique,
  service_name text not null,
  enabled boolean not null default true,
  source_type text not null default 'sms',
  sender_pattern text not null default '',
  sender_match_type text not null default 'contains',
  package_pattern text not null default '',
  title_pattern text not null default '',
  otp_regex text not null default '(?<!\d)(\d{4,8})(?!\d)',
  otp_keyword text not null default '',
  otp_length_min integer not null default 4,
  otp_length_max integer not null default 8,
  wait_timeout_seconds integer not null default 120,
  validity_seconds integer not null default 180,
  device_id text not null default '',
  sim_slot integer,
  auto_fill_enabled boolean not null default true,
  manual_fallback_enabled boolean not null default true,
  priority integer not null default 100,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.otp_requests (
  id bigint generated by default as identity primary key,
  request_id text not null unique,
  service_code text not null,
  job_id text not null default '',
  configuration_id bigint,
  source_type text not null default 'sms',
  requested_at timestamptz not null,
  expires_at timestamptz not null,
  status text not null default 'waiting',
  matched_source_type text,
  matched_source_id text,
  matched_at timestamptz,
  consumed_at timestamptz,
  cancelled_at timestamptz,
  failure_code text,
  code_encrypted text not null default '',
  code_masked text not null default '',
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.otp_events (
  id bigint generated by default as identity primary key,
  request_id text not null,
  event_type text not null,
  source_type text not null default '',
  source_id text not null default '',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null
);

create index if not exists mobile_devices_active_idx on public.mobile_devices (is_active, last_seen_at desc);
create index if not exists mobile_pairing_codes_status_idx on public.mobile_pairing_codes (status, expires_at);
create index if not exists mobile_device_nonces_expires_idx on public.mobile_device_nonces (expires_at);
create index if not exists mobile_device_heartbeats_device_idx on public.mobile_device_heartbeats (device_id, created_at desc);
create index if not exists mobile_sms_received_idx on public.mobile_sms_messages (received_at desc);
create index if not exists mobile_sms_otp_idx on public.mobile_sms_messages (is_otp_candidate, used_for_otp, received_at desc);
create index if not exists mobile_notifications_posted_idx on public.mobile_notifications (posted_at desc);
create index if not exists mobile_commands_device_status_idx on public.mobile_commands (device_id, status, expires_at);
create index if not exists mobile_command_logs_command_idx on public.mobile_command_logs (command_id, created_at desc);
create index if not exists mobile_diagnostics_device_idx on public.mobile_diagnostics (device_id, created_at desc);
create index if not exists otp_requests_status_idx on public.otp_requests (status, service_code, expires_at);
create index if not exists otp_events_request_idx on public.otp_events (request_id, created_at desc);

insert into public.features (code, name, parent_code, sort_order)
values
  ('mobilegateway', 'Mobile Gateway', 'quantriweb', 29),
  ('mobile_gateway.view', 'Xem Mobile Gateway', 'mobilegateway', 291),
  ('mobile_gateway.manage', 'Quan tri Mobile Gateway', 'mobilegateway', 292),
  ('mobile_gateway.devices.view', 'Xem thiet bi Mobile', 'mobilegateway', 293),
  ('mobile_gateway.devices.manage', 'Quan tri thiet bi Mobile', 'mobilegateway', 294),
  ('mobile_gateway.sms.view', 'Xem SMS Mobile', 'mobilegateway', 295),
  ('mobile_gateway.sms.view_content', 'Xem noi dung SMS Mobile', 'mobilegateway', 296),
  ('mobile_gateway.notifications.view', 'Xem thong bao Mobile', 'mobilegateway', 297),
  ('mobile_gateway.notifications.view_content', 'Xem noi dung thong bao Mobile', 'mobilegateway', 298),
  ('mobile_gateway.otp.view', 'Xem OTP Mobile', 'mobilegateway', 299),
  ('mobile_gateway.otp.manage', 'Quan tri OTP Mobile', 'mobilegateway', 300),
  ('mobile_gateway.commands.view', 'Xem lenh Mobile', 'mobilegateway', 301),
  ('mobile_gateway.commands.manage', 'Gui lenh Mobile', 'mobilegateway', 302),
  ('mobile_gateway.audit.view', 'Xem nhat ky Mobile', 'mobilegateway', 303)
on conflict (code) do update
set name = excluded.name,
    parent_code = excluded.parent_code,
    sort_order = excluded.sort_order;

update public.features set name = 'Quan tri he thong' where code = 'quantriweb';

insert into public.user_permissions (user_id, feature_code)
select u.id, f.code
from public.users u
join public.features f on f.code in (
  'mobilegateway',
  'mobile_gateway.view',
  'mobile_gateway.manage',
  'mobile_gateway.devices.view',
  'mobile_gateway.devices.manage',
  'mobile_gateway.sms.view',
  'mobile_gateway.sms.view_content',
  'mobile_gateway.notifications.view',
  'mobile_gateway.notifications.view_content',
  'mobile_gateway.otp.view',
  'mobile_gateway.otp.manage',
  'mobile_gateway.commands.view',
  'mobile_gateway.commands.manage',
  'mobile_gateway.audit.view'
)
where u.role = 'admin'
on conflict do nothing;

insert into public.otp_configurations
(service_code, service_name, enabled, source_type, sender_pattern, sender_match_type,
 otp_regex, otp_keyword, otp_length_min, otp_length_max, wait_timeout_seconds, validity_seconds,
 auto_fill_enabled, manual_fallback_enabled, priority, created_at, updated_at)
values
('onebss', 'OneBSS', true, 'sms', 'VNPT', 'contains',
 '(?<!\d)(\d{4,8})(?!\d)', '', 4, 8, 120, 180, true, true, 10, now(), now())
on conflict (service_code) do update
set service_name = excluded.service_name,
    enabled = excluded.enabled,
    source_type = excluded.source_type,
    sender_pattern = excluded.sender_pattern,
    sender_match_type = excluded.sender_match_type,
    otp_regex = excluded.otp_regex,
    wait_timeout_seconds = excluded.wait_timeout_seconds,
    validity_seconds = excluded.validity_seconds,
    auto_fill_enabled = excluded.auto_fill_enabled,
    manual_fallback_enabled = excluded.manual_fallback_enabled,
    priority = excluded.priority,
    updated_at = now();

alter table public.mobile_devices enable row level security;
alter table public.mobile_pairing_codes enable row level security;
alter table public.mobile_device_nonces enable row level security;
alter table public.mobile_device_policies enable row level security;
alter table public.mobile_device_heartbeats enable row level security;
alter table public.mobile_sms_messages enable row level security;
alter table public.mobile_notifications enable row level security;
alter table public.mobile_commands enable row level security;
alter table public.mobile_command_logs enable row level security;
alter table public.mobile_diagnostics enable row level security;
alter table public.otp_configurations enable row level security;
alter table public.otp_requests enable row level security;
alter table public.otp_events enable row level security;

revoke all on table public.mobile_devices from anon, authenticated;
revoke all on table public.mobile_pairing_codes from anon, authenticated;
revoke all on table public.mobile_device_nonces from anon, authenticated;
revoke all on table public.mobile_device_policies from anon, authenticated;
revoke all on table public.mobile_device_heartbeats from anon, authenticated;
revoke all on table public.mobile_sms_messages from anon, authenticated;
revoke all on table public.mobile_notifications from anon, authenticated;
revoke all on table public.mobile_commands from anon, authenticated;
revoke all on table public.mobile_command_logs from anon, authenticated;
revoke all on table public.mobile_diagnostics from anon, authenticated;
revoke all on table public.otp_configurations from anon, authenticated;
revoke all on table public.otp_requests from anon, authenticated;
revoke all on table public.otp_events from anon, authenticated;

grant select, insert, update, delete on table public.mobile_devices to service_role;
grant select, insert, update, delete on table public.mobile_pairing_codes to service_role;
grant select, insert, update, delete on table public.mobile_device_nonces to service_role;
grant select, insert, update, delete on table public.mobile_device_policies to service_role;
grant select, insert, update, delete on table public.mobile_device_heartbeats to service_role;
grant select, insert, update, delete on table public.mobile_sms_messages to service_role;
grant select, insert, update, delete on table public.mobile_notifications to service_role;
grant select, insert, update, delete on table public.mobile_commands to service_role;
grant select, insert, update, delete on table public.mobile_command_logs to service_role;
grant select, insert, update, delete on table public.mobile_diagnostics to service_role;
grant select, insert, update, delete on table public.otp_configurations to service_role;
grant select, insert, update, delete on table public.otp_requests to service_role;
grant select, insert, update, delete on table public.otp_events to service_role;
grant usage, select on all sequences in schema public to service_role;
