-- Chay file nay trong Supabase Dashboard > SQL Editor.
-- Luu hash mat khau dang nhap dung mot lan, khong thay doi mat khau chinh trong public.users.

create table if not exists public.user_one_time_passwords (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  password_hash text not null,
  created_by text not null default '',
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz,
  revoked_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists user_one_time_passwords_active_idx
on public.user_one_time_passwords (user_id, expires_at desc)
where used_at is null and revoked_at is null;

alter table public.user_one_time_passwords enable row level security;

grant select, insert, update, delete on table public.user_one_time_passwords to service_role;
grant usage, select on sequence public.user_one_time_passwords_id_seq to service_role;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'user_one_time_passwords'
      and policyname = 'backend service can manage one time passwords'
  ) then
    create policy "backend service can manage one time passwords"
    on public.user_one_time_passwords
    for all
    to service_role
    using (true)
    with check (true);
  end if;
end $$;
