-- Chay file nay trong Supabase Dashboard > SQL Editor.
-- Luu y: ung dung hien tai tu quan ly dang nhap rieng, khong dung Supabase Auth.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  full_name text not null,
  employee_code text,
  email text,
  phone text,
  birth_date date,
  gender text,
  department text,
  job_title text,
  password_hash text not null,
  role text not null check (role in ('admin', 'viewer')),
  is_active boolean not null default true,
  must_change_password boolean not null default true,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create unique index if not exists users_username_lower_idx on public.users (lower(username));
create unique index if not exists users_employee_code_lower_idx on public.users (lower(employee_code)) where employee_code is not null;
create unique index if not exists users_email_lower_idx on public.users (lower(email)) where email is not null;

alter table public.users add column if not exists employee_code text;
alter table public.users add column if not exists email text;
alter table public.users add column if not exists phone text;
alter table public.users add column if not exists birth_date date;
alter table public.users add column if not exists gender text;
alter table public.users add column if not exists department text;
alter table public.users add column if not exists job_title text;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor text not null,
  action text not null,
  details text not null,
  created_at timestamptz not null
);

create table if not exists public.website_catalog (
  id bigint generated by default as identity primary key,
  name text not null unique,
  url text not null,
  requires_otp boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create unique index if not exists website_catalog_name_lower_idx on public.website_catalog (lower(name));

create table if not exists public.web_credentials (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  website_id bigint not null references public.website_catalog(id) on delete restrict,
  login_username text not null,
  encrypted_password text not null,
  notes text not null default '',
  created_at timestamptz not null,
  updated_at timestamptz not null,
  unique (user_id, website_id, login_username)
);

create table if not exists public.features (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  parent_code text,
  sort_order integer not null default 0
);

create table if not exists public.user_permissions (
  user_id bigint not null references public.users(id) on delete cascade,
  feature_code text not null references public.features(code) on delete cascade,
  primary key (user_id, feature_code)
);

create table if not exists public.system_roles (
  code text primary key,
  name text not null,
  description text not null default '',
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.system_connections (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  connection_type text not null,
  description text not null default '',
  config jsonb not null default '{}'::jsonb,
  is_active boolean not null default false,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.sql_reports (
  id bigint generated by default as identity primary key,
  ten_bao_cao text not null,
  ma_bao_cao text not null unique,
  cau_lenh_sql text not null,
  cac_tham_so jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists sql_reports_ma_bao_cao_lower_idx
on public.sql_reports (lower(ma_bao_cao));

create table if not exists public.data_regions (
  code text primary key,
  name text not null,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.user_data_permissions (
  user_id bigint not null references public.users(id) on delete cascade,
  region_code text not null references public.data_regions(code) on delete cascade,
  primary key (user_id, region_code)
);

create table if not exists public.work_tasks (
  task_id text primary key,
  ten_cong_viec text not null,
  schedule_type text not null default 'Daily',
  run_time text not null default '07:00',
  weekday text not null default '',
  once_date date,
  group_name text not null default '',
  is_done boolean not null default false,
  is_active boolean not null default true,
  last_notified_date date,
  last_notified_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.login_attempts (
  username text primary key,
  fail_count integer not null default 0,
  last_ip text not null default '',
  last_failed_at timestamptz not null,
  updated_at timestamptz not null
);


-- Service/secret key cua backend se lam viec duoi quyen cao.
-- Neu bat RLS, nen tao policy rieng. Trong giai do noi bo, REST service key co the bypass RLS.
alter table public.users enable row level security;
alter table public.audit_logs enable row level security;
alter table public.website_catalog enable row level security;
alter table public.web_credentials enable row level security;
alter table public.features enable row level security;
alter table public.user_permissions enable row level security;
alter table public.system_roles enable row level security;
alter table public.system_connections enable row level security;
alter table public.data_regions enable row level security;
alter table public.user_data_permissions enable row level security;
alter table public.work_tasks enable row level security;
alter table public.login_attempts enable row level security;
alter table public.sql_reports enable row level security;

grant select, insert, update, delete on public.work_tasks to anon, authenticated, service_role;
grant select, insert, update, delete on public.login_attempts to anon, authenticated, service_role;
grant select, insert, update, delete on public.sql_reports to anon, authenticated, service_role;
grant usage, select on sequence public.sql_reports_id_seq to anon, authenticated, service_role;
